name: prebuild
on:
  push:
    branches:
      - master
permissions:
  contents: write
  deployments: write
env:
  CC: "clang"
  CXX: "clang++"
  npm_config_clang: "1"
jobs:
  macos:
    name: Prebuild Binaries for macOS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - uses: actions/checkout@v4
      - run: npm i
      - name: Prebuild
        run: |
          npm run prebuild -- -t 15.3.5 -r electron --arch arm64 -u ${{ github.token }}
          npm run prebuild -- -t 22.3.27 -r electron --arch arm64 -u ${{ github.token }}
          npm run prebuild -- -t 32.2.5 -r electron --arch arm64 -u ${{ github.token }}
          npm run prebuild -- -t 20.18.0 -r node --arch arm64 -u ${{ github.token }}
          npm run prebuild -- -t 22.15.0 -r node --arch arm64 -u ${{ github.token }}
  macos-x64:
    name: Prebuild Binaries for macOS (x64)
    runs-on: macos-13
    timeout-minutes: 30
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - uses: actions/checkout@v4
      - run: npm i
      - name: Prebuild
        run: |
          npm run prebuild -- -t 15.3.5 -r electron --arch x64 -u ${{github.token}}
          npm run prebuild -- -t 22.3.27 -r electron --arch x64 -u ${{ github.token }}
          npm run prebuild -- -t 32.2.5 -r electron --arch x64 -u ${{github.token}}
          npm run prebuild -- -t 20.18.0 -r node --arch x64 -u ${{github.token}}
          npm run prebuild -- -t 22.15.0 -r node --arch x64 -u ${{github.token}}
  windows:
    name: Prebuild Binaries for Windows
    runs-on: windows-2022
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - uses: actions/checkout@v4
      - run: npm i
      - name: Prebuild
        run: |
          npm run prebuild -- -t 15.3.5 -r electron --arch ia32 -u ${{github.token}}
          npm run prebuild -- -t 15.3.5 -r electron --arch x64 -u ${{github.token}}
          npm run prebuild -- -t 15.3.5 -r electron --arch arm64 -u ${{github.token}}
          npm run prebuild -- -t 22.3.27 -r electron --arch ia32 -u ${{github.token}}
          npm run prebuild -- -t 22.3.27 -r electron --arch x64 -u ${{github.token}}
          npm run prebuild -- -t 22.3.27 -r electron --arch arm64 -u ${{github.token}}
          npm run prebuild -- -t 32.2.5 -r electron --arch ia32 -u ${{github.token}}
          npm run prebuild -- -t 32.2.5 -r electron --arch x64 -u ${{github.token}}
          npm run prebuild -- -t 32.2.5 -r electron --arch arm64 -u ${{github.token}}
          npm run prebuild -- -t 20.18.0 -r node --arch ia32 -u ${{github.token}}
          npm run prebuild -- -t 20.18.0 -r node --arch x64 -u ${{github.token}}
          npm run prebuild -- -t 20.18.0 -r node --arch arm64 -u ${{github.token}}
          npm run prebuild -- -t 22.15.0 -r node --arch ia32 -u ${{github.token}}
          npm run prebuild -- -t 22.15.0 -r node --arch x64 -u ${{github.token}}
          npm run prebuild -- -t 22.15.0 -r node --arch arm64 -u ${{github.token}}
